version: "2"

services:
  caddy:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./template/assets:/srv/assets
    ports:
      - 80:2015
  go:
    build: ./
    ports:
      - 3000:3000
